const projects={
tang:{title:'唐伯虎点秋香',label:'AI古装喜剧短剧 · EP01',items:['项目风格：以古装情境与现代元素的碰撞制造喜剧反差，采用真人感写实影像与竖屏短剧形式。通过人物近景、夸张反应和双人关系镜头呈现角色互动，在古装场景氛围中融入轻快、直接的短视频叙事节奏。','我的职责：主要负责AI影像生成与镜头迭代，根据剧情中的动作、对话与反应需求完成画面落地。重点调整人物表情、视线方向及双人互动，兼顾角色造型的一致性与竖屏构图中的主次关系，让观众清楚看见动作的发生、人物的回应与情境的变化。','制作重点：围绕剧情中的笑点细化人物反应，把握表情变化的幅度、动作与回应的衔接，以及不同角色之间的视觉反差，使生成画面配合剧情节奏。','能力体现：理解喜剧表演中的人物反应和互动关系，将情节信息与喜剧反差转化为具体画面，体现竖屏构图、表演细节调整和AI镜头生成的执行能力。']},
flowers:{title:'十二番花信',label:'AI剧情短剧 · 民国情感叙事 · EP01',items:['项目风格：以民国人物与情境为背景，采用偏写实的三维动画风格。旗袍、舞厅与夜巷建立时代氛围，冷暖光影、人物特写与花卉意象共同呈现含蓄、细腻的情感。','我的职责：主要承担AI影像生成与镜头迭代，依据剧情需求和既定美术方向，将人物状态、场景氛围与动作要求落实为具体镜头画面。','制作重点：在生成与反复调整中，关注角色外形、服装和环境光线的一致性，细化人物神态、视线与动作幅度，使前后镜头在视觉与情绪上自然衔接。','能力体现：理解剧情中的人物关系与情绪变化，并转化为构图、景别和表演细节；积累写实人物类AI短剧的生成经验，体现人物情绪把握、画面氛围控制与连续叙事执行能力。']},
white:{title:'白蛇·争渡',label:'独立全流程创作 · 2026.04',items:["项目风格：采用新中式传统美术动画与皮影剪纸视觉体系，将传统题材转化为具有平面层次、装饰色彩与东方韵味的动态影像。通过角色造型、场景构成和画面节奏建立统一的美术表达。", "我的职责：独立完成选题、剧本改编与风格确定，准备角色和场景美术资产、制作分镜，并完成AI镜头生成、剪辑合成、配音及配乐，输出完整视听短片。", "制作重点：围绕既定美术方向组织角色、场景与镜头，关注剪纸层次、人物动作和镜头衔接，并通过剪辑节奏与声音配合，使视觉风格服务于情节推进。", "能力体现：体现从题材理解、视觉设计到动态影像与声音整合的全流程创作能力，能够独立组织制作环节，将传统美术语言落实为完整短片。"]},
bird:{title:'偷偷养只小金乌',label:'AI量产短剧 · 第1集至第3集',items:["项目风格：采用偏西方奇幻的写实电影感影像，以角色、奇幻元素与环境氛围建立故事世界，结合连续短剧形式推进人物关系与剧情。第1集至第3集属于同一连续剧。", "我的职责：主要负责剧本标注、角色与场景资产生成、镜头生成及粗剪，根据剧情梳理画面需求、组织素材，并将生成镜头衔接为初步成片。", "制作重点：关注连续剧情中的角色造型、场景氛围与镜头信息一致性，依据人物动作和情节顺序调整生成结果，通过粗剪检查镜头衔接与叙事清晰度。", "能力体现：体现AI短剧生产中的文本理解、资产组织与镜头执行能力，能够将剧情需求转化为可用影像素材，并通过粗剪建立连续叙事。"]},
green:{title:'循环“绿岸”',label:'团队原创AIGC短片 · 2026.08',items:["项目风格：团队原创AIGC短片，采用上海美术电影制片厂传统美术片的视觉方向。结合二维手绘感、东方线描与平面色彩构成，营造具有中国传统美术韵味的叙事氛围。", "我的职责：独立负责项目中的AIGC影像制作板块，自主选定上美影画风并寻找对标参考，完成剧本拆解、分镜确定、角色与场景资产生成、镜头生成及粗剪输出。", "制作重点：在十几分钟内容中维持统一美术语言，重点控制跨场景与连续镜头的风格衔接，协调角色、环境和动态效果，使不同段落形成连贯的视觉表达。", "能力体现：体现美术方向选择、参考研究与较长篇幅AI影像执行能力，能够将既定视觉风格贯穿资产、分镜与动态生成，并持续关注整体一致性。"]},
circus:{title:'疯狂马戏人',label:'电影感写实影像 · 视觉开发',items:["项目风格：采用电影感写实影像，结合戏剧性光影与暗黑奇幻元素。自然光下的人物与环境保留生活质感，低照度场景、冷暖色彩对比和局部光线营造紧张与神秘氛围，使现实情境与奇幻画面形成视觉反差。", "我的职责：完成经典电影视觉参考分析与视觉开发，研究构图、焦段关系、光影结构、色彩影调及场面调度，并据此开展镜头设计、一致性控制、动态生成与后期整合。", "制作重点：将参考转化为可执行的镜头方案，协调人物位置、空间关系、光线方向与色彩层次，关注生成画面之间的视觉逻辑，使参考研究落实到具体影像。", "能力体现：体现电影视觉分析、审美判断与参考转化能力，能够从画面中提取构图和影调规律，再结合AI工具完成镜头生成与整体视觉整合。"]}
};
const dialog=document.querySelector('dialog'),content=document.querySelector('#dialog-content');
document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>{const p=projects[button.dataset.open];content.replaceChildren();const label=document.createElement('div');label.className='eyebrow';label.textContent=p.label;const title=document.createElement('h2');title.textContent=p.title;const list=document.createElement('ul');p.items.forEach(text=>{const li=document.createElement('li');li.textContent=text;list.append(li)});const note=document.createElement('p');note.className='subtle';note.textContent=button.dataset.open==='green'?'本页展示末尾“少女化蝶”节选。更多项目成片可在面试或沟通时提供。':'网页展示为部分项目，更多项目成片可在面试或沟通时提供。';content.append(label,title,list,note);dialog.showModal()}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('video').addEventListener('error',()=>{document.querySelector('.video-error').hidden=false});


document.querySelectorAll('video').forEach(video=>video.addEventListener('play',()=>{document.querySelectorAll('video').forEach(other=>{if(other!==video)other.pause()})}));
document.querySelectorAll('video').forEach(video=>video.addEventListener('error',()=>{video.parentElement.querySelector('.video-error').hidden=false}));

function observeLoad(video,load){if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){load();observer.disconnect()}},{rootMargin:'150px'});observer.observe(video)}else load()}
function statusFor(video){const status=document.createElement('p');status.className='load-status';status.textContent='正在加载视频…';status.setAttribute('role','status');video.parentElement.append(status);return status;}
document.querySelectorAll('video:not(#video-green)').forEach(video=>{const source=video.querySelector('source');if(!source)return;const url=source.getAttribute('src');source.remove();video.load();video.controls=false;let started=false;observeLoad(video,async()=>{if(started)return;started=true;const status=statusFor(video);try{const response=await fetch(url);if(!response.ok)throw Error();const blob=await response.blob();video.src=URL.createObjectURL(blob);video.controls=true;video.addEventListener('loadedmetadata',()=>status.remove(),{once:true});video.load()}catch(e){status.textContent='视频加载失败，请刷新重试。'}})});
const greenVideo=document.querySelector('#video-green');let greenStarted=false;
async function loadGreen(){if(greenStarted)return;greenStarted=true;const status=statusFor(greenVideo);try{const base='';const manifest=await fetch(base+'manifest.json').then(r=>{if(!r.ok)throw Error();return r.json()});if(!window.MediaSource||!MediaSource.isTypeSupported(manifest.mime)){const files=await Promise.all(['init.mp4',...manifest.parts].map(async name=>{const r=await fetch(base+name);if(!r.ok)throw Error();return r.blob()}));greenVideo.src=URL.createObjectURL(new Blob(files,{type:'video/mp4'}));greenVideo.addEventListener('loadedmetadata',()=>status.remove(),{once:true});greenVideo.load();return;}const media=new MediaSource();greenVideo.src=URL.createObjectURL(media);await new Promise(resolve=>media.addEventListener('sourceopen',resolve,{once:true}));const buffer=media.addSourceBuffer(manifest.mime);async function append(name){const response=await fetch(base+name);if(!response.ok)throw Error();const data=await response.arrayBuffer();await new Promise((resolve,reject)=>{function done(){cleanup();resolve()}function fail(){cleanup();reject(Error())}function cleanup(){buffer.removeEventListener('updateend',done);buffer.removeEventListener('error',fail)}buffer.addEventListener('updateend',done);buffer.addEventListener('error',fail);buffer.appendBuffer(data)})}await append('init.mp4');media.duration=manifest.duration;const loaded=new Set();while(loaded.size<manifest.parts.length){const target=Math.min(manifest.parts.length-1,Math.floor(greenVideo.currentTime/manifest.segmentDuration));let index=[target,target+1].find(i=>i<manifest.parts.length&&!loaded.has(i));if(index===undefined)index=manifest.parts.findIndex((_,i)=>!loaded.has(i));await append(manifest.parts[index]);loaded.add(index);if(loaded.has(0))status.remove();}if(media.readyState==='open')media.endOfStream();}catch(e){status.textContent='视频加载失败，请刷新重试。';greenVideo.parentElement.querySelector('.video-error').hidden=false;}}
observeLoad(greenVideo,loadGreen);
